apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-viola
spec:
  storageClassName: manual #creating conflicts
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

